disabled_rules:
    - identifier_name
    - line_length
    - todo
    - trailing_whitespace

cyclomatic_complexity:
    ignores_case_statements: true

function_parameter_count:
    warning: 6
    error: 8

nesting:
    type_level:
        warning: 3
        error: 6
    statement_level:
        warning: 5
        error: 10
