disabled_rules:
    - identifier_name
    - line_length
    - todo

cyclomatic_complexity:
    ignores_case_statements: true

function_parameter_count:
    warning: 6
    error: 8

nesting:
    type_level:
        warning: 3
        error: 6
    function_level:
        warning: 5
        error: 10

custom_rules:
    already_true:
        regex: "== true"
        message: "Don't compare to true, just use the bool value."

    already_bool:
        regex: "== false"
        message: "Don't compare to false, just use !value."

    numbers_smell:
        regex: '(return |case |\w\(|: |\?\? |\, |== |<=? |>=? |\+= |\-= |\/= |\*= |%= |\w\.\w+ = )\(*-?\d{2,}'
        message: "Numbers smell; define a constant instead."
        excluded: '.*Tests/'

    non_weak_delegate_datasource:
        included: ".*.swift"
        name: "Retain Cycle"
        regex: '^\ *var\ *(delegate)'
        message: "Delegate/datasource may be weak."
        severity: warning

#Project-specific
    final_classes:
        included: ".*.swift"
        name: "Final classes"
        regex: "(?<!final )class [a-zA-Z]*(ViewModel|Service)"
        message: "ViewModels, Models and Services classes should be final"
        severity: warning

    update_on_main:
        included: ".*.swift"
        name: "Update on main"
        regex: "objectWillChange.send\\(\\)"
        message: "Objects should update on main thread. Please use sendOnMain() instead"
        severity: warning
